### PR TITLE
fix bug in livelock detection - Closes #102

### LINKED ISSUE #102: Livelock detection should support nonlinear input
Currently, livelock warning is printed for a reaction with a nonlinear input pattern, such as

```scala
go { case a(x) + a(y) => a(x+y) }
```

Livelock detection should take into account that this reaction requires two copies of `a` but emits only one (if that can be reliably detected).

### PR DESCRIPTION
**Pull request by winitzki**
Livelock detection routine had a simple error - a `fold` did not use the accumulator in its body.

### CODE REVIEW

File: core/src/main/scala/io/chymyst/jc/StaticAnalysis.scala [hunk 1]
```diff
@@ -36,8 +36,8 @@ private[jc] object StaticAnalysis {
 
   private def inputMatchersWeakerThanOutput(isWeaker: (InputMoleculeInfo, OutputMoleculeInfo) => Option[Boolean])
                                            (input: List[InputMoleculeInfo], output: Array[OutputMoleculeInfo]): Boolean = {
-    input.flatFoldLeft[Array[OutputMoleculeInfo]](output) { (acc, inputInfo) =>
-      output
+    input.flatFoldLeft(output) { (acc, inputInfo) ⇒
+      acc
```
Comment (winitzki) [inline core/src/main/scala/io/chymyst/jc/StaticAnalysis.scala:40]: This was the error.
